sudo: false
language: node_js
node_js:
  - "4.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
# Send coverage data to Coveralls
after_success: "cat ./test_reports/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
